import type { Contact } from "../types";
import { dateFromNow, daysFromNow } from "../utils";

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "contact-1",
    name: "高橋 誠",
    name_kana: "タカハシ マコト",
    company: "株式会社ミライテック",
    department: "情報システム部",
    title: "部長",
    email: "takahashi@miraitech.example.com",
    phone: "03-1234-5678",
    mobile: "090-1111-2222",
    address: "東京都港区芝公園1-2-3",
    website: "https://miraitech.example.com",
    tags: ["決裁者", "IT", "重要顧客"],
    memo: "サポート体制を重視。ゴルフが趣味。",
    card_image_url: "",
    exchanged_at: dateFromNow(-45),
    owner_name: "田中 美咲",
    created_at: daysFromNow(-45),
  },
  {
    id: "contact-2",
    name: "渡辺 由紀",
    name_kana: "ワタナベ ユキ",
    company: "グローバル商事株式会社",
    department: "購買部",
    title: "課長",
    email: "watanabe@global-trade.example.com",
    phone: "03-9876-5432",
    mobile: "",
    address: "東京都千代田区丸の内2-3-4",
    website: "https://global-trade.example.com",
    tags: ["窓口担当", "商社"],
    memo: "レスポンスが早い。メール連絡を好む。",
    card_image_url: "",
    exchanged_at: dateFromNow(-30),
    owner_name: "山田 花子",
    created_at: daysFromNow(-30),
  },
  {
    id: "contact-3",
    name: "小林 亮",
    name_kana: "コバヤシ リョウ",
    company: "株式会社ネクストステージ",
    department: "営業企画部",
    title: "マネージャー",
    email: "kobayashi@nextstage.example.com",
    phone: "06-1111-3333",
    mobile: "080-3333-4444",
    address: "大阪府大阪市北区梅田1-1-1",
    website: "",
    tags: ["キーマン", "SaaS"],
    memo: "SFA導入の推進役。データドリブンな提案が刺さる。",
    card_image_url: "",
    exchanged_at: dateFromNow(-10),
    owner_name: "鈴木 大輔",
    created_at: daysFromNow(-10),
  },
  {
    id: "contact-4",
    name: "中村 恵",
    name_kana: "ナカムラ メグミ",
    company: "さくらフーズ株式会社",
    department: "カスタマーサポート部",
    title: "主任",
    email: "nakamura@sakura-foods.example.com",
    phone: "045-222-3333",
    mobile: "",
    address: "神奈川県横浜市西区みなとみらい3-3-3",
    website: "https://sakura-foods.example.com",
    tags: ["展示会", "食品"],
    memo: "展示会ブースで名刺交換。コスト削減に関心。",
    card_image_url: "",
    exchanged_at: dateFromNow(-6),
    owner_name: "伊藤 翔",
    created_at: daysFromNow(-6),
  },
  {
    id: "contact-5",
    name: "加藤 剛",
    name_kana: "カトウ ツヨシ",
    company: "東海精密工業株式会社",
    department: "生産技術部",
    title: "次長",
    email: "kato@tokai-seimitsu.example.com",
    phone: "052-444-5555",
    mobile: "090-5555-6666",
    address: "愛知県名古屋市中区栄4-5-6",
    website: "https://tokai-seimitsu.example.com",
    tags: ["製造", "決裁者", "紹介"],
    memo: "既存顧客からの紹介。現場のDX化に課題感。数字で示す資料を好む。",
    card_image_url: "",
    exchanged_at: dateFromNow(-60),
    owner_name: "佐藤 健太",
    created_at: daysFromNow(-60),
  },
  {
    id: "contact-6",
    name: "藤田 沙織",
    name_kana: "フジタ サオリ",
    company: "株式会社アドクリエイト",
    department: "クリエイティブ本部",
    title: "プロデューサー",
    email: "fujita@adcreate.example.com",
    phone: "03-6666-7777",
    mobile: "080-7777-8888",
    address: "東京都渋谷区神南1-7-8",
    website: "https://adcreate.example.com",
    tags: ["広告", "パートナー"],
    memo: "共同セミナーの企画パートナー候補。SNSプロモーションに強い。",
    card_image_url: "",
    exchanged_at: dateFromNow(-21),
    owner_name: "田中 美咲",
    created_at: daysFromNow(-21),
  },
  {
    id: "contact-7",
    name: "松本 一樹",
    name_kana: "マツモト カズキ",
    company: "ライトハウス不動産株式会社",
    department: "経営企画室",
    title: "室長",
    email: "matsumoto@lighthouse-re.example.com",
    phone: "092-888-9999",
    mobile: "",
    address: "福岡県福岡市博多区博多駅前2-9-1",
    website: "https://lighthouse-re.example.com",
    tags: ["不動産", "キーマン", "セミナー"],
    memo: "自社セミナーに参加。店舗網の業務効率化を検討中。来月フォロー予定。",
    card_image_url: "",
    exchanged_at: dateFromNow(-3),
    owner_name: "鈴木 大輔",
    created_at: daysFromNow(-3),
  },
  {
    id: "contact-8",
    name: "石井 菜々",
    name_kana: "イシイ ナナ",
    company: "メディカルブリッジ株式会社",
    department: "事業開発部",
    title: "係長",
    email: "ishii@medical-bridge.example.com",
    phone: "011-222-1111",
    mobile: "070-1234-5678",
    address: "北海道札幌市中央区北一条西3-3-3",
    website: "",
    tags: ["医療", "窓口担当", "展示会"],
    memo: "ヘルスケアEXPOで名刺交換。導入事例の資料送付を約束。院内稟議は3ヶ月程度。",
    card_image_url: "",
    exchanged_at: dateFromNow(-1),
    owner_name: "伊藤 翔",
    created_at: daysFromNow(-1),
  },
];
