import type { Deal, DealActivity } from "../types";
import { dateFromNow, daysFromNow } from "../utils";

export const DEMO_DEALS: Deal[] = [
  {
    id: "deal-1",
    name: "基幹システム連携プロジェクト",
    company: "株式会社ミライテック",
    contact_name: "高橋 誠",
    stage: "negotiation",
    amount: 4_800_000,
    probability: 70,
    expected_close: dateFromNow(14),
    owner_name: "田中 美咲",
    next_action: "決裁者向け最終見積の提出（今週金曜まで）",
    memo: "競合はA社。価格よりサポート体制を重視している。",
    updated_at: daysFromNow(-1),
    created_at: daysFromNow(-45),
  },
  {
    id: "deal-2",
    name: "年間保守契約リニューアル",
    company: "グローバル商事株式会社",
    contact_name: "渡辺 由紀",
    stage: "proposal",
    amount: 2_400_000,
    probability: 50,
    expected_close: dateFromNow(30),
    owner_name: "山田 花子",
    next_action: "提案書ドラフトを渡辺様へ送付",
    memo: "現行契約は他社。乗り換え検討中で予算取りは済んでいる。",
    updated_at: daysFromNow(-2),
    created_at: daysFromNow(-30),
  },
  {
    id: "deal-3",
    name: "SFA導入支援（50ライセンス）",
    company: "株式会社ネクストステージ",
    contact_name: "小林 亮",
    stage: "qualified",
    amount: 1_800_000,
    probability: 30,
    expected_close: dateFromNow(45),
    owner_name: "鈴木 大輔",
    next_action: "オンラインデモの日程調整",
    memo: "テレアポから発掘。営業部長が乗り気。",
    updated_at: daysFromNow(-3),
    created_at: daysFromNow(-10),
  },
  {
    id: "deal-4",
    name: "コールセンター代行プラン",
    company: "さくらフーズ株式会社",
    contact_name: "中村 恵",
    stage: "lead",
    amount: 900_000,
    probability: 10,
    expected_close: dateFromNow(60),
    owner_name: "伊藤 翔",
    next_action: "資料送付後のフォローコール",
    memo: "展示会で名刺交換。まずは情報収集フェーズ。",
    updated_at: daysFromNow(-4),
    created_at: daysFromNow(-6),
  },
  {
    id: "deal-5",
    name: "業務効率化ツール導入",
    company: "東都物流株式会社",
    contact_name: "加藤 剛",
    stage: "won",
    amount: 3_200_000,
    probability: 100,
    expected_close: dateFromNow(-7),
    owner_name: "田中 美咲",
    next_action: "キックオフMTGの設定",
    memo: "受注済み。オンボーディングへ引き継ぎ。",
    updated_at: daysFromNow(-7),
    created_at: daysFromNow(-90),
  },
  {
    id: "deal-6",
    name: "Web広告運用代行（6ヶ月）",
    company: "株式会社アオバ企画",
    contact_name: "松本 拓也",
    stage: "lost",
    amount: 1_500_000,
    probability: 0,
    expected_close: dateFromNow(-14),
    owner_name: "伊藤 翔",
    next_action: "半年後に再アプローチ（リマインダー設定済み）",
    memo: "価格面で競合B社に決定。運用体制の評価は高かったため再挑戦の余地あり。",
    updated_at: daysFromNow(-12),
    created_at: daysFromNow(-60),
  },
  {
    id: "deal-7",
    name: "人材紹介サービス年間契約",
    company: "株式会社ヒカリ人材",
    contact_name: "森田 彩",
    stage: "proposal",
    amount: 2_800_000,
    probability: 40,
    expected_close: dateFromNow(21),
    owner_name: "佐藤 健太",
    next_action: "稟議用の費用対効果資料を作成して送付",
    memo: "初回提案の反応は良好。決裁は取締役会で来月上旬の見込み。",
    updated_at: daysFromNow(-4),
    created_at: daysFromNow(-20),
  },
  {
    id: "deal-8",
    name: "営業研修プログラム提供",
    company: "北陸精機株式会社",
    contact_name: "石川 直樹",
    stage: "won",
    amount: 1_200_000,
    probability: 100,
    expected_close: dateFromNow(-3),
    owner_name: "鈴木 大輔",
    next_action: "初回研修日程の確定と講師アサイン",
    memo: "3ヶ月の集合研修＋eラーニングのセット。来期の継続提案も視野。",
    updated_at: daysFromNow(-3),
    created_at: daysFromNow(-75),
  },
];

export const DEMO_DEAL_ACTIVITIES: DealActivity[] = [
  {
    id: "act-1",
    deal_id: "deal-1",
    type: "meeting",
    note: "2回目の商談。技術要件はクリア、あとは価格交渉のみ。",
    author_name: "田中 美咲",
    created_at: daysFromNow(-1, 15),
  },
  {
    id: "act-2",
    deal_id: "deal-1",
    type: "stage_change",
    note: "提案 → 交渉 に進行",
    author_name: "田中 美咲",
    created_at: daysFromNow(-1, 16),
  },
  {
    id: "act-3",
    deal_id: "deal-2",
    type: "mail",
    note: "概算見積と導入スケジュール案を送付",
    author_name: "山田 花子",
    created_at: daysFromNow(-2, 11),
  },
  {
    id: "act-4",
    deal_id: "deal-3",
    type: "call",
    note: "小林様と15分通話。デモは来週希望とのこと。",
    author_name: "鈴木 大輔",
    created_at: daysFromNow(-3, 14),
  },
  {
    id: "act-5",
    deal_id: "deal-5",
    type: "stage_change",
    note: "交渉 → 受注 に変更",
    author_name: "田中 美咲",
    created_at: daysFromNow(-7, 10),
  },
  {
    id: "act-6",
    deal_id: "deal-4",
    type: "mail",
    note: "会社案内と導入事例集を送付。開封通知あり。",
    author_name: "伊藤 翔",
    created_at: daysFromNow(-5, 9, 30),
  },
  {
    id: "act-7",
    deal_id: "deal-2",
    type: "visit",
    note: "現行システムの課題ヒアリングで訪問。更新月は9月と判明。",
    author_name: "山田 花子",
    created_at: daysFromNow(-6, 13),
  },
  {
    id: "act-8",
    deal_id: "deal-6",
    type: "stage_change",
    note: "提案 → 失注 に変更",
    author_name: "伊藤 翔",
    created_at: daysFromNow(-12, 17),
  },
  {
    id: "act-9",
    deal_id: "deal-6",
    type: "note",
    note: "価格面で競合B社に決定との連絡。半年後に再アプローチ予定。",
    author_name: "伊藤 翔",
    created_at: daysFromNow(-12, 17, 15),
  },
  {
    id: "act-10",
    deal_id: "deal-7",
    type: "meeting",
    note: "初回提案を実施。森田様の反応は良好、稟議は来月の取締役会。",
    author_name: "佐藤 健太",
    created_at: daysFromNow(-4, 11),
  },
  {
    id: "act-11",
    deal_id: "deal-8",
    type: "stage_change",
    note: "交渉 → 受注 に変更",
    author_name: "鈴木 大輔",
    created_at: daysFromNow(-3, 15),
  },
  {
    id: "act-12",
    deal_id: "deal-1",
    type: "call",
    note: "高橋様と価格条件について電話。値引きは5%が上限と回答。",
    author_name: "田中 美咲",
    created_at: daysFromNow(-2, 10),
  },
];
