import type { SalesDocument } from "../types";
import { daysFromNow } from "../utils";

export const DEMO_DOCUMENTS: SalesDocument[] = [
  {
    id: "doc-1",
    name: "標準提案書テンプレート_v3",
    category: "proposal",
    file_url: "",
    file_type: "pptx",
    size_kb: 4200,
    description: "全商材共通の提案書テンプレート。表紙・課題整理・ROI試算のスライド構成。",
    tags: ["テンプレート", "全商材"],
    uploaded_by: "佐藤 健太",
    downloads: 42,
    created_at: daysFromNow(-60),
  },
  {
    id: "doc-2",
    name: "2026年度 料金表（正式版）",
    category: "pricing",
    file_url: "",
    file_type: "pdf",
    size_kb: 820,
    description: "4月改定後の正式料金表。値引きルールは最終ページ参照。",
    tags: ["料金", "2026年度"],
    uploaded_by: "佐藤 健太",
    downloads: 67,
    created_at: daysFromNow(-30),
  },
  {
    id: "doc-3",
    name: "東都物流様向け提案書_final",
    category: "case_study",
    file_url: "",
    file_type: "pdf",
    size_kb: 3600,
    description: "受注に至った実提案書。ROIの見せ方が特に参考になる。",
    tags: ["成功事例", "物流業界"],
    uploaded_by: "田中 美咲",
    downloads: 28,
    created_at: daysFromNow(-14),
  },
  {
    id: "doc-4",
    name: "サービス紹介ムービー用トークガイド",
    category: "manual",
    file_url: "",
    file_type: "docx",
    size_kb: 340,
    description: "デモ動画を見せながら話すときの補足トーク集。",
    tags: ["デモ", "トーク"],
    uploaded_by: "鈴木 大輔",
    downloads: 15,
    created_at: daysFromNow(-8),
  },
  {
    id: "doc-5",
    name: "導入事例集 2026上期（製造・物流・小売 10社）",
    category: "case_study",
    file_url: "",
    file_type: "pdf",
    size_kb: 5800,
    description:
      "業界別の導入事例を10社分まとめたパンフレット。商談の中盤で業界が近い事例を見せると刺さりやすい。",
    tags: ["事例", "パンフレット", "業界別"],
    uploaded_by: "山田 花子",
    downloads: 33,
    created_at: daysFromNow(-21),
  },
  {
    id: "doc-6",
    name: "見積もりシミュレーター（自動計算）",
    category: "pricing",
    file_url: "",
    file_type: "xlsx",
    size_kb: 260,
    description:
      "ユーザー数・オプションを入力すると月額と年間割引が自動計算されるExcel。黄色セルのみ編集可。",
    tags: ["見積", "計算ツール"],
    uploaded_by: "伊藤 翔",
    downloads: 51,
    created_at: daysFromNow(-12),
  },
  {
    id: "doc-7",
    name: "秘密保持契約書（NDA）ひな形",
    category: "contract",
    file_url: "",
    file_type: "docx",
    size_kb: 88,
    description: "法務確認済みの標準NDAひな形。条文を変更する場合は必ず法務へ相談すること。",
    tags: ["契約", "法務確認済み"],
    uploaded_by: "佐藤 健太",
    downloads: 19,
    created_at: daysFromNow(-45),
  },
  {
    id: "doc-8",
    name: "展示会用 販促物データ一式",
    category: "other",
    file_url: "",
    file_type: "zip",
    size_kb: 48200,
    description: "ノベルティ・のぼり・パネルの入稿データ一式。展示会出展時はここから最新版を使用。",
    tags: ["展示会", "販促"],
    uploaded_by: "田中 美咲",
    downloads: 6,
    created_at: daysFromNow(-2),
  },
];
