import type { CalendarEvent } from "../types";
import { daysFromNow } from "../utils";

export const DEMO_EVENTS: CalendarEvent[] = [
  {
    id: "ev-1",
    title: "株式会社ミライテック 訪問商談",
    description: "新プラン提案。決裁者の情報システム部長も同席予定。",
    start_at: daysFromNow(0, 10, 0),
    end_at: daysFromNow(0, 11, 30),
    all_day: false,
    category: "visit",
    location: "東京都港区 ミライテック本社",
    owner_name: "田中 美咲",
    created_at: daysFromNow(-7),
  },
  {
    id: "ev-2",
    title: "週次営業会議",
    description: "今週のパイプラインレビューと数字報告",
    start_at: daysFromNow(0, 16, 0),
    end_at: daysFromNow(0, 17, 0),
    all_day: false,
    category: "meeting",
    location: "会議室A / Zoom",
    owner_name: "佐藤 健太",
    created_at: daysFromNow(-14),
  },
  {
    id: "ev-3",
    title: "テレアポ集中タイム",
    description: "新規リスト50件アタック",
    start_at: daysFromNow(1, 9, 30),
    end_at: daysFromNow(1, 12, 0),
    all_day: false,
    category: "call",
    location: "",
    owner_name: "鈴木 大輔",
    created_at: daysFromNow(-3),
  },
  {
    id: "ev-4",
    title: "グローバル商事 見積提出期限",
    description: "値引き条件は佐藤MGR承認済みの範囲で",
    start_at: daysFromNow(2, 0, 0),
    end_at: daysFromNow(2, 23, 59),
    all_day: true,
    category: "deadline",
    location: "",
    owner_name: "山田 花子",
    created_at: daysFromNow(-5),
  },
  {
    id: "ev-5",
    title: "SaaSツール勉強会（代理店向け）",
    description: "新機能アップデートの共有会",
    start_at: daysFromNow(3, 14, 0),
    end_at: daysFromNow(3, 15, 30),
    all_day: false,
    category: "meeting",
    location: "オンライン",
    owner_name: "伊藤 翔",
    created_at: daysFromNow(-2),
  },
  {
    id: "ev-6",
    title: "北斗製作所 フォロー訪問",
    description: "導入後1ヶ月の活用状況ヒアリング。追加ライセンスの打診も。",
    start_at: daysFromNow(1, 14, 0),
    end_at: daysFromNow(1, 15, 30),
    all_day: false,
    category: "visit",
    location: "神奈川県横浜市 北斗製作所 本社工場",
    owner_name: "山田 花子",
    created_at: daysFromNow(-6),
  },
  {
    id: "ev-7",
    title: "営業部 懇親会",
    description: "新メンバー歓迎会を兼ねて。会費は当日集金。",
    start_at: daysFromNow(-1, 19, 0),
    end_at: daysFromNow(-1, 21, 0),
    all_day: false,
    category: "other",
    location: "恵比寿 炉端やまと",
    owner_name: "佐藤 健太",
    created_at: daysFromNow(-10),
  },
  {
    id: "ev-8",
    title: "アクア食品 オンライン商談",
    description: "2回目の商談。前回の宿題（他社事例の共有）を冒頭で回答する。",
    start_at: daysFromNow(4, 11, 0),
    end_at: daysFromNow(4, 12, 0),
    all_day: false,
    category: "meeting",
    location: "Google Meet",
    owner_name: "田中 美咲",
    created_at: daysFromNow(-4),
  },
  {
    id: "ev-9",
    title: "既存顧客フォローコール",
    description: "契約更新3ヶ月前の顧客リスト12件に架電。解約兆候の早期検知。",
    start_at: daysFromNow(5, 13, 0),
    end_at: daysFromNow(5, 15, 0),
    all_day: false,
    category: "call",
    location: "",
    owner_name: "伊藤 翔",
    created_at: daysFromNow(-3),
  },
  {
    id: "ev-10",
    title: "サンライズ不動産 初回訪問",
    description: "テレアポから獲得したアポ。まずは課題ヒアリング中心で。",
    start_at: daysFromNow(7, 10, 30),
    end_at: daysFromNow(7, 12, 0),
    all_day: false,
    category: "visit",
    location: "千葉県船橋市 サンライズ不動産 本店",
    owner_name: "鈴木 大輔",
    created_at: daysFromNow(-2),
  },
  {
    id: "ev-11",
    title: "四半期目標レビュー会議",
    description: "Q2の着地見込みとQ3のターゲット設定。各自パイプライン資料持参。",
    start_at: daysFromNow(8, 15, 0),
    end_at: daysFromNow(8, 17, 0),
    all_day: false,
    category: "meeting",
    location: "会議室B",
    owner_name: "佐藤 健太",
    created_at: daysFromNow(-8),
  },
  {
    id: "ev-12",
    title: "ミライテック 提案書提出期限",
    description: "訪問商談の内容を反映した最終版。提出前に佐藤MGRのレビュー必須。",
    start_at: daysFromNow(9, 0, 0),
    end_at: daysFromNow(9, 23, 59),
    all_day: true,
    category: "deadline",
    location: "",
    owner_name: "田中 美咲",
    created_at: daysFromNow(-1),
  },
];
