import type { TaskItem } from "../types";
import { dateFromNow, daysFromNow } from "../utils";

export const DEMO_TASKS: TaskItem[] = [
  {
    id: "task-1",
    title: "ミライテック向け最終見積書の作成",
    description: "値引き上限はMGR承認済みの8%まで。サポートプラン比較表も添付する。",
    status: "doing",
    priority: "high",
    due_date: dateFromNow(2),
    assignee_name: "田中 美咲",
    related_deal: "基幹システム連携プロジェクト",
    completed_at: null,
    created_at: daysFromNow(-2),
  },
  {
    id: "task-2",
    title: "新規リスト50件のテレアポ",
    description: "IT業界リスト。トークスクリプトv2を使用。",
    status: "todo",
    priority: "mid",
    due_date: dateFromNow(3),
    assignee_name: "鈴木 大輔",
    related_deal: "",
    completed_at: null,
    created_at: daysFromNow(-1),
  },
  {
    id: "task-3",
    title: "グローバル商事 提案書ドラフト",
    description: "過去の類似事例（東都物流）の数字を引用する。",
    status: "todo",
    priority: "high",
    due_date: dateFromNow(5),
    assignee_name: "山田 花子",
    related_deal: "年間保守契約リニューアル",
    completed_at: null,
    created_at: daysFromNow(-3),
  },
  {
    id: "task-4",
    title: "展示会名刺のデータ化（32枚）",
    description: "名刺管理へ登録し、フォローメールの対象を選定。",
    status: "done",
    priority: "low",
    due_date: dateFromNow(-1),
    assignee_name: "伊藤 翔",
    related_deal: "",
    completed_at: daysFromNow(-1, 18),
    created_at: daysFromNow(-5),
  },
  {
    id: "task-5",
    title: "週次レポートの提出",
    description: "今週のKPI集計とパイプライン更新。",
    status: "todo",
    priority: "mid",
    due_date: dateFromNow(1),
    assignee_name: "佐藤 健太",
    related_deal: "",
    completed_at: null,
    created_at: daysFromNow(-1),
  },
  {
    id: "task-6",
    title: "ネクストステージ社 トライアル環境の設定確認",
    description: "50ライセンス分のアカウント発行状況を確認し、デモシナリオを準備する。",
    status: "todo",
    priority: "high",
    due_date: dateFromNow(-2),
    assignee_name: "鈴木 大輔",
    related_deal: "SFA導入支援（50ライセンス）",
    completed_at: null,
    created_at: daysFromNow(-6),
  },
  {
    id: "task-7",
    title: "さくらフーズ 定例ミーティングのアジェンダ作成",
    description: "前回の宿題事項（応対品質レポート）への回答を含める。",
    status: "doing",
    priority: "mid",
    due_date: dateFromNow(0),
    assignee_name: "伊藤 翔",
    related_deal: "コールセンター代行プラン",
    completed_at: null,
    created_at: daysFromNow(-2, 14),
  },
  {
    id: "task-8",
    title: "提案書テンプレートを最新版に差し替え",
    description: "料金改定を反映したテンプレートを営業資料フォルダへ反映する。",
    status: "todo",
    priority: "low",
    due_date: "",
    assignee_name: "佐藤 健太",
    related_deal: "",
    completed_at: null,
    created_at: daysFromNow(-4),
  },
  {
    id: "task-9",
    title: "東都物流 導入効果ヒアリングの日程調整",
    description: "事例化の承諾取得もあわせて依頼する。",
    status: "done",
    priority: "high",
    due_date: dateFromNow(0),
    assignee_name: "田中 美咲",
    related_deal: "業務効率化ツール導入",
    completed_at: daysFromNow(0, 10, 30),
    created_at: daysFromNow(-3),
  },
  {
    id: "task-10",
    title: "失注案件の振り返りメモ作成",
    description: "競合が選定された理由を整理してナレッジへ共有する。",
    status: "done",
    priority: "mid",
    due_date: dateFromNow(-3),
    assignee_name: "山田 花子",
    related_deal: "",
    completed_at: daysFromNow(0, 9),
    created_at: daysFromNow(-7),
  },
  {
    id: "task-11",
    title: "ミライテック 高橋様へ御礼メール送付",
    description: "昨日の商談の御礼と次回アジェンダの共有。",
    status: "todo",
    priority: "high",
    due_date: dateFromNow(-1),
    assignee_name: "田中 美咲",
    related_deal: "基幹システム連携プロジェクト",
    completed_at: null,
    created_at: daysFromNow(-1, 18),
  },
  {
    id: "task-12",
    title: "来期キャンペーンのターゲットリスト精査",
    description: "既存顧客のアップセル候補を抽出し、優先度スコアを付ける。",
    status: "doing",
    priority: "low",
    due_date: dateFromNow(7),
    assignee_name: "鈴木 大輔",
    related_deal: "",
    completed_at: null,
    created_at: daysFromNow(-2),
  },
];
